name: Rust Monorepo CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[SKIP CI]')"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - name: Install liblzma (Linux only)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y liblzma-dev

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build (release)
      run: cargo build --release

    - name: Upload Windows binary
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: abe_multitool-windows
        path: target/release/abe_multitool.exe

    - name: Upload Linux binary
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: abe_multitool-linux
        path: target/release/abe_multitool